### ISSUE TITLE
Add finally clause support to pipeline definitions

### ISSUE THREAD

**Issue by bnallapeta** [praxis-ai-toolkit/praxis#41]
## Issue

Currently, there's no way to ensure certain steps run after a pipeline completes, regardless of intermediate step success/failure. If any step in a dependency chain fails, subsequent steps never execute.

## Proposed Solution
Add support for a finally clause in pipeline YAML definitions, similar to try-catch-finally in programming languages.

```
steps:
  - name: provision_infrastructure
    plugin: libi_infra_provisioner
    fail_on_error: true
    
  - name: deploy_model
    plugin: model_deployer  
    depends_on: [provision_infrastructure]
    fail_on_error: false

  - name: cleanup_resources
    plugin: resource_cleaner
    depends_on: [provision_infrastructure]
    fail_on_error: false
    finally: true  # New field - runs after pipeline completes
```

## Implementation pointers
- Extend pipeline YAML schema to support finally field in a plugin
- Update DAG executor to run `finally: true` plugin after main pipeline completes
- Support conditional execution within finally steps (optional)
- Maintain backward compatibility
